function plotCharges(ax, charges)
    % Plot point charges on the axes
    if isempty(charges.x), return; end
    
    for i = 1:length(charges.x)
        if charges.q(i) > 0
            color = [1 0 0]; % red
            text_sign = '+';
        else
            color = [0 0 1]; % blue
            text_sign = '-';
        end

        plot(ax, charges.x(i), charges.y(i), 'o', ...
             'MarkerSize', 12, ...
             'MarkerFaceColor', color, ...
             'MarkerEdgeColor', 'k', ...
             'LineWidth', 2);

        text(ax, charges.x(i), charges.y(i), ...
             sprintf('%s%.1f', text_sign, abs(charges.q(i))), ...
             'HorizontalAlignment', 'center', ...
             'VerticalAlignment', 'middle', ...
             'Color', 'white', ...
             'FontWeight', 'bold', ...
             'FontSize', 8);
    end
end
